# Generated by Django 2.1.1 on 2018-10-09 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('city', models.TextField()),
                ('clubName', models.TextField()),
                ('member1', models.CharField(max_length=255)),
                ('member2', models.CharField(max_length=255)),
                ('member3', models.CharField(max_length=255)),
                ('tournamentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Tournament')),
            ],
        ),
    ]
