# Generated by Django 2.1.1 on 2018-10-09 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='city',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='team',
            name='clubName',
            field=models.CharField(max_length=512),
        ),
    ]
