# Generated by Django 2.1.1 on 2018-11-01 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20181009_0211'),
    ]

    operations = [
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prop', models.CharField(max_length=30)),
                ('opp', models.CharField(max_length=30)),
                ('PM', models.CharField(max_length=30)),
                ('OL', models.CharField(max_length=30)),
                ('PW', models.CharField(max_length=30)),
                ('OW', models.CharField(max_length=30)),
                ('DPM', models.CharField(max_length=30)),
                ('DLO', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.CharField(max_length=30)),
                ('proposition', models.CharField(max_length=30)),
                ('opposition', models.CharField(max_length=30)),
                ('chair', models.CharField(max_length=255)),
                ('panelist', models.CharField(max_length=1024)),
                ('decision', models.CharField(max_length=30)),
                ('points', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Points')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Tournament')),
                ('win', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Team')),
            ],
        ),
    ]
