# Generated by Django 2.1.1 on 2018-11-13 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_points_round'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('clubID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Club')),
            ],
        ),
        migrations.CreateModel(
            name='JudgePoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.FloatField()),
                ('judgeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Judge')),
            ],
        ),
        migrations.CreateModel(
            name='MatchUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judgeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Judge')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('clubID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Club')),
            ],
        ),
        migrations.CreateModel(
            name='MemberPoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StylePoints', models.FloatField()),
                ('ContentPoints', models.FloatField()),
                ('StratergyPoints', models.FloatField()),
                ('memberID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Member')),
            ],
        ),
        migrations.RemoveField(
            model_name='round',
            name='opposition',
        ),
        migrations.RemoveField(
            model_name='round',
            name='panelist',
        ),
        migrations.RemoveField(
            model_name='round',
            name='points',
        ),
        migrations.RemoveField(
            model_name='round',
            name='proposition',
        ),
        migrations.RemoveField(
            model_name='team',
            name='member1',
        ),
        migrations.RemoveField(
            model_name='team',
            name='member2',
        ),
        migrations.RemoveField(
            model_name='team',
            name='member3',
        ),
        migrations.AddField(
            model_name='round',
            name='statement',
            field=models.CharField(default='default', max_length=4096),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='round',
            name='chair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Judge'),
        ),
        migrations.AlterField(
            model_name='round',
            name='decision',
            field=models.CharField(choices=[('Split', 'Split'), ('Unaminous', 'Unaminous')], default='Split', max_length=20),
        ),
        migrations.AlterField(
            model_name='round',
            name='round',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='team',
            name='clubName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Club'),
        ),
        migrations.DeleteModel(
            name='Points',
        ),
        migrations.AddField(
            model_name='memberpoints',
            name='roundID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Round'),
        ),
        migrations.AddField(
            model_name='member',
            name='teamID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Team'),
        ),
        migrations.AddField(
            model_name='matchup',
            name='oppID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opposition', to='api.Team'),
        ),
        migrations.AddField(
            model_name='matchup',
            name='propID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposition', to='api.Team'),
        ),
        migrations.AddField(
            model_name='matchup',
            name='roundID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Round'),
        ),
        migrations.AddField(
            model_name='judgepoints',
            name='roundID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Round'),
        ),
        migrations.AddField(
            model_name='judge',
            name='teamID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Team'),
        ),
    ]
