# Generated by Django 2.1.1 on 2019-01-31 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20181113_0325'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='chair',
            field=models.CharField(default='Ron', max_length=4096),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='round',
            name='decision',
            field=models.CharField(choices=[('Split', 'Split'), ('Unaminous', 'Unaminous')], default='Split', max_length=20),
        ),
        migrations.AddField(
            model_name='round',
            name='win',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Team'),
        ),
    ]
