# Generated by Django 2.1.1 on 2018-12-06 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20181113_0325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='judge',
            name='teamID',
        ),
        migrations.AddField(
            model_name='judge',
            name='tournamentID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Tournament'),
        ),
    ]
