# Generated by Django 2.1.1 on 2019-02-11 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20190131_2250'),
        ('api', '0007_auto_20181206_0130'),
    ]

    operations = [
    ]
