# Generated by Django 2.1.1 on 2019-02-13 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_merge_20190211_0241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='clubName',
            new_name='clubID',
        ),
    ]
