# Generated by Django 2.1.7 on 2019-02-20 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20190213_1757'),
    ]

    operations = [
        migrations.RenameField(
            model_name='round',
            old_name='tournament',
            new_name='tournamentID',
        ),
        migrations.RemoveField(
            model_name='round',
            name='decision',
        ),
        migrations.RemoveField(
            model_name='round',
            name='win',
        ),
    ]
