export const FETCH_TOURNAMENTS_START = 'FETCH_TOURNAMENTS_START';

export const FETCH_TOURNAMENTS_SUCCESS = 'FETCH_TOURNAMENTS_SUCCESS';

export const FETCH_TOURNAMENTS_FAILURE = 'FETCH_TOURNAMENTS_FAILURE';

export const ADD_TOURNAMENT_START = 'ADD_TOURNAMENT_START';

export const ADD_TOURNAMENT_SUCCESS = 'ADD_TOURNAMENT_SUCCESS';

export const ADD_TOURNAMENTS_FAILURE = 'ADD_TOURNAMENTS_FAILURE';
